- name: Ensure the namespace exists
  community.kubernetes.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Apply the Deployment manifest
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', '01_deployment.yml.j2') }}"

- name: Apply the Service manifest
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', '02_service.yml.j2') }}"

- name: Apply the Ingress manifest
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', '03_ingress.yml.j2') }}"