{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "demo.fullname" . }}-reader
  labels:
    {{- include "demo.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["events", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "demo.fullname" . }}-reader
  labels:
    {{- include "demo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "demo.fullname" . }}-reader
subjects:
- kind: ServiceAccount
  name: {{ include "demo.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}