# argo-cd/application.yaml
# This manifest defines the Argo CD Application for the GitOps workflow.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # The name of the application in the Argo CD UI.
  name: hello-app-prod
  # This application resource must be created in the 'argocd' namespace.
  namespace: argo
spec:
  # The Argo CD project this application belongs to.
  # MODIFIED: Point to our new, dedicated project.
  project: hello-app-project

  # Source defines the location of the application's configuration.
  source:
    # The URL of your GitHub repository.
    repoURL: 'https://github.com/tyreyalv/cicd-portfolio.git'
    # The branch to track for changes.
    targetRevision: main
    # The path within the repo where the deployment configuration is located.
    path: ansible

    # This section tells Argo CD to use its Ansible plugin to render the manifests.
    plugin:
      name: ansible

  # Destination defines where the application will be deployed.
  destination:
    # The target cluster URL. 'https://kubernetes.default.svc' means the same cluster where Argo CD is running.
    server: 'https://kubernetes.default.svc'
    # The namespace to deploy the application's resources into.
    # This should match the 'namespace' variable in your ansible/group_vars/all.yml file.
    namespace: 'hello-app'

  # SyncPolicy defines how Argo CD synchronizes the application state.
  syncPolicy:
    automated:
      # Automatically prune resources that are no longer defined in Git.
      prune: true
      # Automatically sync the application when it is out of sync with Git.
      selfHeal: true
    # This sync option will automatically create the destination namespace if it doesn't exist.
    syncOptions:
      - CreateNamespace=true
